/**
 * Icons sorted by name
 */
export enum IconMap {
  'ActualBalanceIcon',
  'AppleIcon',
  'Calendar2Icon',
  'CalendarCircleIcon',
  'CalendarIcon',
  'CalendarTickIcon',
  'CalendarWhiteIcon',
  'CardIcon',
  'CardPosIcon',
  'CardTickIcon',
  'CardWithGemIcon',
  'ChartSquareIcon',
  'ClockIcon',
  'ComfortableCompIcon',
  'CreditCardsIcon',
  'DocIcon',
  'DocumentTextIcon',
  'DollarIcon',
  'EarthIcon',
  'EmptyWalletChangeIcon',
  'EmptyWalletIcon',
  'EmptyWalletWhiteIcon',
  'EuroIcon',
  'GlassIcon',
  'GlobalIcon',
  'GridIcon',
  'GridIconWhite',
  'InterestGrowthIcon',
  'InterestIcon',
  'JCBIcon',
  'LoupeIcon',
  'MasterCardIcon',
  'MinusIcon',
  'MirIcon',
  'MoneyIcon',
  'MoneyInsuranceIcon',
  'MonitorMobileIcon',
  'NewDocIcon',
  'OfficeIcon',
  'OkIcon',
  'PassSendIcon',
  'PercentageRoundIcon',
  'PercentageSquareIcon',
  'PercentageSquareWhiteIcon',
  'PersonalCardIcon',
  'PlayMarketIcon',
  'PlusIcon',
  'Profile2UserIcon',
  'ProfileIcon',
  'RoundRubleIcon',
  'SafeIcon',
  'ShieldTickIcon',
  'SignDocsIcon',
  'SmallClockIcon',
  'TelegramIcon',
  'UnionPayIcon',
  'UserTickIcon',
  'VisaIcon',
  'VKIcon',
  'WalletAdd',
  'WalletAdd2',
  'WalletIcon',
  'WalletWithMoneyIcon',
}

/**
 * @title Иконка
 * @enumNames [
 *    "Деньги",
 *    "Лого «Apple»",
 *    "Календарь 2",
 *    "Скруглённый календарь",
 *    "Календарь",
 *    "Календарь с галочкой",
 *    "Календарь белый",
 *    "Кред. карта",
 *    "Кред. карта под наклоном",
 *    "Кред. карта с галочкой",
 *    "Карта с драгоценностями",
 *    "Деньги внутри кошелька",
 *    "Часы",
 *    "Кресло",
 *    "Скидка",
 *    "Кредитные карты",
 *    "Огромная скидка",
 *    "Документ",
 *    "Документ с текстом",
 *    "Доллар",
 *    "Пустой кошелёк с возвратом",
 *    "Пустой кошелёк",
 *    "Пустой кошелёк (белый)",
 *    "Евро",
 *    "Зеркало",
 *    "Глобус",
 *    "Сетка",
 *    "Сетка (белая)",
 *    "Диаграмма роста",
 *    "Скидка",
 *    "JCB",
 *    "Лупа",
 *    "MasterCard",
 *    "Минус",
 *    "МИР",
 *    "Деньги",
 *    "Денежное страхование",
 *    "Монитор и мобильный",
 *    "Новый документ",
 *    "Офис",
 *    "Лого «Одноклассники»",
 *    "Бизнес",
 *    "Проценты (круг.)",
 *    "Проценты",
 *    "Проценты белые",
 *    "Персональная карта",
 *    "Лого «PlayMarket»",
 *    "Плюс",
 *    "Профиль, 2 персоны",
 *    "Профиль",
 *    "Рубль (круг.)",
 *    "Сейф",
 *    "Безопасность",
 *    "Подписанные документы",
 *    "Маленькие часы",
 *    "Лого «Telegram»",
 *    "UnionPay",
 *    "Пользователь",
 *    "Visa",
 *    "Лого «VK»",
 *    "Пополнение карты",
 *    "Кошелёк с плюсом",
 *    "Кошелёк",
 *    "Кошелёк с деньгами",
 *  ]
 */
export type IconName = keyof typeof IconMap;

export interface IconProps {
  className?: string;
  name: IconName;
  alt?: string;
  title?: string;
  width?: string;
  height?: string;
  asSVG?: boolean;
}
